apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 1Gi
  # volumeMode field requires BlockVolume Alfa feature gate to be enabled
  volumeMode: Filesystem
  accessModes:
    - ReadWrightMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage # the same like in pvc
  local: 
    path: /mnt
  nodeAffinity:  # explain where is an our local volume
    requared:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values: 
              - minikube.s000001.edu.slurm.io
